services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mern-network
  server:
    container_name: server
    build:
      context: ./mern/server
    image: yoismak/mern-server:latest
    ports:
      - "5050:5050"
    environment:
      ATLAS_URI: ${ATLAS_URI}
      PORT: ${PORT}
    depends_on:
      - mongodb
    networks:
      - mern-network
  client:
    container_name: client
    build:
      context: ./mern/client
    image: yoismak/mern-client:latest
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - mern-network
volumes:
  mongodb_data:
networks:
  mern-network:
    driver: bridge