name: CD Pipeline
on:
    workflow_run:
        workflows: ["CI Pipeline"]
        types:
            - completed
jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Setup Environment Variables
              run: |
                  echo "ATLAS_URI=${{ secrets.ATLAS_URI }}" >> .env
                  echo "PORT=${{ secrets.PORT }}" >> .env

            - name: Pull Docker Images
              run: docker compose pull

            - name: Start Containers
              run: docker compose up -d
