name: CD Pipeline
on:
    workflow_run:
        workflows: ["CI Pipeline"]
        types:
            - completed
jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Login to Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Pull Docker Images
              run: |
                  docker pull yoismak/mern-server:latest
                  docker pull yoismak/mern-client:latest
                  docker pull mongo
            - name: Stop Containers
              run: |
                  docker stop $(docker ps -q) || true
                  docker rm $(docker ps -aq) || true
            - name: Start Containers
              run: docker compose up -d
