name: CI Pipeline

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        environment: cicd
        steps:
            - uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push Docker images
              env:
                  ATLAS_URI: ${{ secrets.ATLAS_URI }}
                  PORT: ${{ secrets.PORT }}
              run: |
                  docker compose build
                  docker compose push
